### ISSUE TITLE
[Feature request] StudioRack integration

### ISSUE THREAD

**Issue by kmturley** [creativeintent/mxzero#2]
I'm the lead developer of an open-source VST plugin manager called StudioRack:
https://github.com/studiorack

The aim of my project is to provide a free open-source way to manage VST plugin dependencies and their versions. I would love to add Temper to the StudioRack Registry, which would involve the following steps:

1. Publish a Github release containing the plugin source along with metadata plugins.json
2. Tag your Github repository with studiorack-plugin so it can be discovered
3. Wait for the studiorack-registry to index your plugin (every 24 hours)
4. Check the registry feed for your plugin to appear https://studiorack.github.io/studiorack-registry/

Wondering if you would be interested in collaborating to make this work? It would then allow users to install Temper using the StudioRack website, command-line tool or app?

Thanks!

**Comment by nick-thompson** [comment]
Hey @kmturley thanks for the plug! Looks very cool. I was just checking through the site and it looks like Temper's already on there? https://studiorack.github.io/studiorack-site/plugins/studiorack_plugin-temper_temper

**Comment by kmturley** [comment]
Yep, I added it yesterday
https://github.com/studiorack/studiorack-registry/commit/649bbc3df8590891c7fdcc04cdcc3de60a38b6f6#diff-7aebb122a6ea8a2749d60cb05b7e103c9eae6e2e85e48d2d6cd9e20b63013975R578

I'm using your binaries along with your name. I don't think this violates the GPL-3 license? Let me know if you disagree.

**Comment by nick-thompson** [comment]
Very cool, thanks! I'm not sure about the license either, but it's no problem for me either way in this case
