### ISSUE TITLE
Faust source for TemperDsp.cpp?

### ISSUE THREAD

**Issue by m-roberts** [creativeintent/mxzero#4]
```
Code generated with Faust 2.5.32 (https://faust.grame.fr)
Compilation options: cpp, -scal -ftz 0
```

I am trying to learn how to make an application like this, but it seems as though the original source for the DSP is not provided?

**Comment by nick-thompson** [comment]
Oh sure, it's right here https://github.com/creativeintent/temper/blob/master/Dsp/temper.dsp!

(See https://github.com/creativeintent/temper/blob/master/Makefile#L14).

I'll close this as I think that answers the question, but please feel free to reopen if I missed something.

**Comment by m-roberts** [comment]
So sorry. Still learning a lot about all of this tech stack. Thanks a lot!
